
execute_process(COMMAND octave-config -p OCTLIBDIR RESULT_VARIABLE OCTAVE_CONFIG_RES OUTPUT_VARIABLE OCTAVE_LIBDIR OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND octave-config -p OCTINCLUDEDIR OUTPUT_VARIABLE OCTAVE_INCDIR OUTPUT_STRIP_TRAILING_WHITESPACE)

IF(NOT ${OCTAVE_CONFIG_RES} MATCHES "0")
  MESSAGE("Error running octave-config.  Is it installed and in the PATH?  Result: " ${OCTAVE_CONFIG_RES})
ENDIF(NOT ${OCTAVE_CONFIG_RES} MATCHES "0")

FIND_PATH(OCTAVE_INCLUDE_DIR octave/oct.h
  PATHS
  ${OCTAVE_INCDIR}
  ${OCTAVE_INCDIR}/..
)

FIND_LIBRARY(OCTAVE_LIBRARIES 
  NAMES octave
  PATHS ${OCTAVE_LIBDIR}
)

SET(OCTAVE_FOUND "NO")
IF(OCTAVE_LIBRARIES AND OCTAVE_INCLUDE_DIR)
  SET(OCTAVE_FOUND "YES")
ENDIF(OCTAVE_LIBRARIES AND OCTAVE_INCLUDE_DIR)

