FIND_PATH(RSVP_INCLUDE_DIR /home/jkimball/projects/rsvp/src/
  PATHS
  NO_DEFAULT_PATH
)

FIND_LIBRARY(RSVP_LIBRARY 
  NAMES rsvp
  PATHS /home/jkimball/projects/rsvp/build/
    NO_DEFAULT_PATH
)

SET(RSVP_FOUND "NO")
IF(RSVP_LIBRARY AND RSVP_INCLUDE_DIR)
  SET(RSVP_FOUND "YES")
ENDIF(RSVP_LIBRARY AND RSVP_INCLUDE_DIR)
