// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/colormap.proto

#ifndef PROTOBUF_protocol_2fcolormap_2eproto__INCLUDED
#define PROTOBUF_protocol_2fcolormap_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace RemoteKinect {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protocol_2fcolormap_2eproto();
void protobuf_AssignDesc_protocol_2fcolormap_2eproto();
void protobuf_ShutdownFile_protocol_2fcolormap_2eproto();

class ColorMap;

// ===================================================================

class ColorMap : public ::google::protobuf::Message {
 public:
  ColorMap();
  virtual ~ColorMap();
  
  ColorMap(const ColorMap& from);
  
  inline ColorMap& operator=(const ColorMap& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ColorMap& default_instance();
  
  void Swap(ColorMap* other);
  
  // implements Message ----------------------------------------------
  
  ColorMap* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ColorMap& from);
  void MergeFrom(const ColorMap& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string source_serial = 1;
  inline bool has_source_serial() const;
  inline void clear_source_serial();
  static const int kSourceSerialFieldNumber = 1;
  inline const ::std::string& source_serial() const;
  inline void set_source_serial(const ::std::string& value);
  inline void set_source_serial(const char* value);
  inline void set_source_serial(const char* value, size_t size);
  inline ::std::string* mutable_source_serial();
  inline ::std::string* release_source_serial();
  
  // required uint32 tick = 2;
  inline bool has_tick() const;
  inline void clear_tick();
  static const int kTickFieldNumber = 2;
  inline ::google::protobuf::uint32 tick() const;
  inline void set_tick(::google::protobuf::uint32 value);
  
  // required int32 width = 3;
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 3;
  inline ::google::protobuf::int32 width() const;
  inline void set_width(::google::protobuf::int32 value);
  
  // required int32 height = 4;
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 4;
  inline ::google::protobuf::int32 height() const;
  inline void set_height(::google::protobuf::int32 value);
  
  // repeated fixed32 pixels = 5 [packed = true];
  inline int pixels_size() const;
  inline void clear_pixels();
  static const int kPixelsFieldNumber = 5;
  inline ::google::protobuf::uint32 pixels(int index) const;
  inline void set_pixels(int index, ::google::protobuf::uint32 value);
  inline void add_pixels(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      pixels() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_pixels();
  
  // @@protoc_insertion_point(class_scope:RemoteKinect.ColorMap)
 private:
  inline void set_has_source_serial();
  inline void clear_has_source_serial();
  inline void set_has_tick();
  inline void clear_has_tick();
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_height();
  inline void clear_has_height();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* source_serial_;
  ::google::protobuf::uint32 tick_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > pixels_;
  mutable int _pixels_cached_byte_size_;
  ::google::protobuf::int32 height_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_protocol_2fcolormap_2eproto();
  friend void protobuf_AssignDesc_protocol_2fcolormap_2eproto();
  friend void protobuf_ShutdownFile_protocol_2fcolormap_2eproto();
  
  void InitAsDefaultInstance();
  static ColorMap* default_instance_;
};
// ===================================================================


// ===================================================================

// ColorMap

// required string source_serial = 1;
inline bool ColorMap::has_source_serial() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ColorMap::set_has_source_serial() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ColorMap::clear_has_source_serial() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ColorMap::clear_source_serial() {
  if (source_serial_ != &::google::protobuf::internal::kEmptyString) {
    source_serial_->clear();
  }
  clear_has_source_serial();
}
inline const ::std::string& ColorMap::source_serial() const {
  return *source_serial_;
}
inline void ColorMap::set_source_serial(const ::std::string& value) {
  set_has_source_serial();
  if (source_serial_ == &::google::protobuf::internal::kEmptyString) {
    source_serial_ = new ::std::string;
  }
  source_serial_->assign(value);
}
inline void ColorMap::set_source_serial(const char* value) {
  set_has_source_serial();
  if (source_serial_ == &::google::protobuf::internal::kEmptyString) {
    source_serial_ = new ::std::string;
  }
  source_serial_->assign(value);
}
inline void ColorMap::set_source_serial(const char* value, size_t size) {
  set_has_source_serial();
  if (source_serial_ == &::google::protobuf::internal::kEmptyString) {
    source_serial_ = new ::std::string;
  }
  source_serial_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ColorMap::mutable_source_serial() {
  set_has_source_serial();
  if (source_serial_ == &::google::protobuf::internal::kEmptyString) {
    source_serial_ = new ::std::string;
  }
  return source_serial_;
}
inline ::std::string* ColorMap::release_source_serial() {
  clear_has_source_serial();
  if (source_serial_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = source_serial_;
    source_serial_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required uint32 tick = 2;
inline bool ColorMap::has_tick() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ColorMap::set_has_tick() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ColorMap::clear_has_tick() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ColorMap::clear_tick() {
  tick_ = 0u;
  clear_has_tick();
}
inline ::google::protobuf::uint32 ColorMap::tick() const {
  return tick_;
}
inline void ColorMap::set_tick(::google::protobuf::uint32 value) {
  set_has_tick();
  tick_ = value;
}

// required int32 width = 3;
inline bool ColorMap::has_width() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ColorMap::set_has_width() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ColorMap::clear_has_width() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ColorMap::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline ::google::protobuf::int32 ColorMap::width() const {
  return width_;
}
inline void ColorMap::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
}

// required int32 height = 4;
inline bool ColorMap::has_height() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ColorMap::set_has_height() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ColorMap::clear_has_height() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ColorMap::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline ::google::protobuf::int32 ColorMap::height() const {
  return height_;
}
inline void ColorMap::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
}

// repeated fixed32 pixels = 5 [packed = true];
inline int ColorMap::pixels_size() const {
  return pixels_.size();
}
inline void ColorMap::clear_pixels() {
  pixels_.Clear();
}
inline ::google::protobuf::uint32 ColorMap::pixels(int index) const {
  return pixels_.Get(index);
}
inline void ColorMap::set_pixels(int index, ::google::protobuf::uint32 value) {
  pixels_.Set(index, value);
}
inline void ColorMap::add_pixels(::google::protobuf::uint32 value) {
  pixels_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ColorMap::pixels() const {
  return pixels_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ColorMap::mutable_pixels() {
  return &pixels_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace RemoteKinect

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protocol_2fcolormap_2eproto__INCLUDED
